version: '3'
services:

  postgres:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "artie"
      POSTGRES_PASSWORD: "31415"
      POSTGRES_DB: "sales-api"

