services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: salesapi-app
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis

  db:
    build: .docker/postgres
    container_name: salesapi-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "artie"
      POSTGRES_PASSWORD: "31415"
      POSTGRES_DB: "salesapi-db"
    volumes:
      - sales-api:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:latest'
    container_name: salesapi-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  sales-api:
